### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by printHello-world** [xiaozhangtongx/WHUT-JKRBTB#1]
同学你好！我是武汉理工机电学院研二的一个学生，最近学习了一段时间的python，想搞一下学校的打卡，所以在github上看到了你的代码，但是我发现这个代码无法实现。正常情况那个打卡页面用电脑网页点开总是报用户信息不存在，所以我用fiddler抓了电脑版微信的小程序的包，但是出现了一些问题。方便请教你一下吗，加一下我QQ1019564311，也可以有偿，这个坎我纠结了一天发现了点问题，但是自己不会弄

**Comment by xiaozhangtongx** [comment]
学长/姐，你好
首先声明一下：这份代码最开始是我是在逛gitee时偶然发现的，我只是在他的基础上留下了关键部分，原始的代码我也在readme给出了链接。
其次，运行这个程序的时候需要先将自己的健康日报账号与微信解绑。
然后，需要在python文件里面输入学长/姐你的学号，和你的账号的密码，运行这个python文件应该就可以填报，我这里是没有错误的。
针对用户信息不存在这个问题，我想学长/姐你应该直接打开了代码里面健康日报打卡的网页url，我之前也尝试过在浏览器直接输入账号和密码，也是无法登录，我不清楚是不是只有用微信才能或者只有有管理员权限的人才可以，所以我现在每天的健康打卡只能通过定时运行这个python来解决。

**Comment by printHello-world** [comment]
非常感谢你能给我回信，作为一个非计算机专业的我太难了。。。我明天先不打卡了跑一下你这个源码，非常感谢。我也去gitee上看了原作者的代码，目前python还在下载PyQt5，慢的要死...我自己弄了半天想通过微信小程序抓包，但是在第一步的post时候总是返回openId失败，查了查好像这个小程序在绑定微信时会生成一个code，就是我给你发过去的那个截图的base64解码的东西，查了很多也没弄明白，放弃了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 晚上10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] for help (Issue #1)





 
学长/姐，你好
 首先声明一下：这份代码最开始是我是在逛gitee时偶然发现的，我只是在他的基础上留下了关键部分，原始的代码我也在readme给出了链接。
 其次，运行这个程序的时候需要先将自己的健康日报账号与微信解绑。
 然后，需要在python文件里面输入学长/姐你的学号，和你的账号的密码，运行这个python文件应该就可以填报，我这里是没有错误的。
 针对用户信息不存在这个问题，我想学长/姐你应该直接打开了代码里面健康日报打卡的网页url，我之前也尝试过在浏览器直接输入账号和密码，也是无法登录，我不清楚是不是只有用微信才能或者只有有管理员权限的人才可以，所以我现在每天的健康打卡只能通过定时运行这个python来解决。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by printHello-world** [comment]
非常感谢你能给我回信，作为一个非计算机专业的我太难了。。。我明天先不打卡了跑一下你这个源码，非常感谢。我也去gitee上看了原作者的代码，目前python还在下载PyQt5，慢的要死...我自己弄了半天想通过微信小程序抓包，但是在第一步的post时候总是返回openId失败，查了查好像这个小程序在绑定微信时会生成一个code，就是我给你发过去的那个截图的base64解码的东西，查了很多也没弄明白，放弃了
还有一个问题是我是20级的，我们登录的时候用的是身份证号，不是学号，不知道这个会不会有影响




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 晚上10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] for help (Issue #1)





 
学长/姐，你好
 首先声明一下：这份代码最开始是我是在逛gitee时偶然发现的，我只是在他的基础上留下了关键部分，原始的代码我也在readme给出了链接。
 其次，运行这个程序的时候需要先将自己的健康日报账号与微信解绑。
 然后，需要在python文件里面输入学长/姐你的学号，和你的账号的密码，运行这个python文件应该就可以填报，我这里是没有错误的。
 针对用户信息不存在这个问题，我想学长/姐你应该直接打开了代码里面健康日报打卡的网页url，我之前也尝试过在浏览器直接输入账号和密码，也是无法登录，我不清楚是不是只有用微信才能或者只有有管理员权限的人才可以，所以我现在每天的健康打卡只能通过定时运行这个python来解决。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaozhangtongx** [comment]
emm，应该没影响吧。只要微信能登录，那么这个应该就可以。
