### ISSUE TITLE
邮件发送失败

### ISSUE THREAD

**Issue by FXM12581** [xiaozhangtongx/WHUT-JKRBTB#10]
打开能成功，就是邮件发送失败，密码什么的也没错不知道为什么。
之前对github不是很熟悉，那个request是我不小心弄的，非常不好意思，给你带来麻烦了。

**Comment by xiaozhangtongx** [comment]
没事的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 上午10:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiaozhangtongx/WHUT-JKRBTB] 邮件发送失败 (Issue #10)





 
打开能成功，就是邮件发送失败，密码什么的也没错不知道为什么。
 之前对github不是很熟悉，那个request是我不小心弄的，非常不好意思，给你带来麻烦了。
