### ISSUE TITLE
填报失败了，进行加密了吗？

### ISSUE THREAD

**Issue by kmcheno** [xiaozhangtongx/WHUT-JKRBTB#11]

**Comment by xiaozhangtongx** [comment]
有可能，现在获取不到session ID了





------------------ 原始邮件 ------------------
发件人: kmcheno ***@***.***&gt;
发送时间: 2022年3月30日 17:46
收件人: xiaozhangtongx/WHUT-JKRBTB ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xiaozhangtongx/WHUT-JKRBTB] 填报失败了，进行加密了吗？ (Issue #11)

**Comment by okamiwaw** [comment]
我这里也是获取不到sessionID了，有什么方法可以破解吗
