### ISSUE TITLE
重写了遍程序，修复自动填报

### ISSUE THREAD

**Issue by ChrisKimZHT** [xiaozhangtongx/WHUT-JKRBTB#13]
作者码风和我有点区别，改起来有点不习惯，所以就不fork了再pr了，干脆自己写了遍：
https://github.com/ChrisKimZHT/WHUT-AutoHealthReport

**Comment by xiaozhangtongx** [comment]
可以，强



---原始邮件---
发件人: "Haotian ***@***.***&gt;
发送时间: 2022年4月28日(周四) 中午12:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xiaozhangtongx/WHUT-JKRBTB] 重写了遍程序，修复自动填报 (Issue #13)




 
作者码风和我有点区别，改起来有点不习惯，所以就不fork了再pr了，干脆自己写了遍：
 https://github.com/ChrisKimZHT/WHUT-AutoHealthReport
