### ISSUE TITLE
有时候打卡会不成功

### ISSUE THREAD

**Issue by Alan-wa** [xiaozhangtongx/WHUT-JKRBTB#2]
我把代码部署在腾讯云函数上，服务器返回{'status': False, 'code': 50005, 'message': '对象未经初始化或不存在', 'data': None, 'otherData': {'detail': None}}，实际上也是没有填报成功让我很苦恼。

**Comment by xiaozhangtongx** [comment]
这是来自QQ邮箱的自动回复邮件，无需回复！你好，我已经收到了你给我发的邮件，谢谢！！!                                                  张居富

**Comment by xiaozhangtongx** [comment]
![image](https://user-images.githubusercontent.com/63902256/148628307-c3e0f6b5-5dcd-419e-8323-7a108c27f824.png)
你好，请问同学你的账号和密码是不是输入正确了，我这里是可以打卡成功的，并没有报50005的错误

**Comment by Alan-wa** [comment]
现在好了，不过返乡后忘记改地址好几天了，被辅导员打电话询问了/facepalm/facepalm
老哥是返乡后手动改地址吗？

**Comment by xiaozhangtongx** [comment]
> 现在好了，不过返乡后忘记改地址好几天了，被辅导员打电话询问了/facepalm/facepalm 老哥是返乡后手动改地址吗？

对的哈，地址要自己修改，这个没有开启定位服务的
