### ISSUE TITLE
初始发送邮件的邮箱是作者的机器人邮箱吗

### ISSUE THREAD

**Issue by Greed-zero** [xiaozhangtongx/WHUT-JKRBTB#3]
QAQ，才发现用那个邮箱发了好多邮件，谢谢大佬的脚本，以后就不用去点那个憨憨填报了

**Comment by xiaozhangtongx** [comment]
对，因为能力和时间有限，那个邮箱是我建立的一个小号，哈哈哈，以后可以尝试升级为短信服务，哈哈哈
