### ISSUE TITLE
研究生的运行完之后结果如下

### ISSUE THREAD

**Issue by Hades2WH** [xiaozhangtongx/WHUT-JKRBTB#7]
![image](https://user-images.githubusercontent.com/93966743/156304170-fb455e6f-137c-4cd4-bcd7-d918da8f1ccc.png)
已经通过手机端打过卡后再次运行该程序，不知道程序内是否有问题

**Comment by xiaozhangtongx** [comment]
你好，学长请问你微信小程序推出登录了吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月2日(周三) 下午2:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)




 

 已经通过手机端打过卡后再次运行该程序，不知道程序内是否有问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hades2WH** [comment]
退出了

**Comment by xiaozhangtongx** [comment]
那学长，你明天在试试看看，我觉得应该没有问题的呀😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月2日(周三) 下午2:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)




 
退出了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hades2WH** [comment]
好的好的，明天有问题再说

**Comment by Hades2WH** [comment]
今天程序运行一遍之后还是这个结果，请问是哪里除了问题呢

**Comment by xiaozhangtongx** [comment]
我等一下回去看看哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月3日(周四) 中午11:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)




 
今天程序运行一遍之后还是这个结果，请问是哪里除了问题呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaozhangtongx** [comment]
![image](https://user-images.githubusercontent.com/63902256/156504687-e1bf15ab-b97c-4e46-9940-bb5b010893ce.png)
学长，我这边运行好像没有错误呀，请学长你检查一下以下这几个方面的问题：
1.手机上的微信小程序没有退出登录
2.账号和密码有没有输入错误
3.地址格式有没有输入错误
4.学长你打印一下源码中的res,看看到底是什么情况
![image](https://user-images.githubusercontent.com/63902256/156505080-f8ec4d20-106a-4d5e-9381-748d8a3f84c6.png)

**Comment by Hades2WH** [comment]
你好，这是打印后的结果

地址格式如上，在小程序端已经取消关联，账号和密码没有错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午1:56
***@***.***&gt;;
抄送:&nbsp;"Goodbye ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)





 

 学长，我这边运行好像没有错误呀，请学长你检查一下以下这几个方面的问题：
 1.手机上的微信小程序没有退出登录
 2.账号和密码有没有输入错误
 3.地址格式有没有输入错误
 4.学长你打印一下源码中的res,看看到底是什么情况
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaozhangtongx** [comment]
我这好像没有收到打印的结果，还有一种情况，会不会是研究生的系统和本科生的不同？？？

**Comment by Hades2WH** [comment]
有可能是的，这个脚本有其他研究生成功使用过的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 下午2:10
***@***.***&gt;;
抄送:&nbsp;"Goodbye ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)





 
我这好像没有收到打印的结果，还有一种情况，会不会是研究生的系统和本科生的不同？？？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaozhangtongx** [comment]
应该有吧，不太清楚，哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)





 有可能是的，这个脚本有其他研究生成功使用过的吗 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年3月3日(星期四) 下午2:10 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;"Goodbye ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7) 
 
 
 
 
 
   
 我这好像没有收到打印的结果，还有一种情况，会不会是研究生的系统和本科生的不同？？？ 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hades2WH** [comment]
嗯嗯，那就这样吧，麻烦了你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 下午2:17
***@***.***&gt;;
抄送:&nbsp;"Goodbye ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)





 应该有吧，不太清楚，哈哈哈 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年3月3日(星期四) 下午2:16 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7) 
 
 
 
 
 
  有可能是的，这个脚本有其他研究生成功使用过的吗  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "xiaozhangtongx/WHUT-JKRBTB"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年3月3日(星期四) 下午2:10  
  ***@***.***&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Goodbye ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [xiaozhangtongx/WHUT-JKRBTB] 研究生的运行完之后结果如下 (Issue #7)  
   
   
   
   
   
     
  我这好像没有收到打印的结果，还有一种情况，会不会是研究生的系统和本科生的不同？？？  
     
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.   
  You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeremyheung** [comment]
研究生系统不是同一个 ，可以看看我的fork项目，改成了研究生版本
