### ISSUE TITLE
打卡失败，小程序登录显示非法请求

### ISSUE THREAD

**Issue by Shmily-zd** [xiaozhangtongx/WHUT-JKRBTB#8]
![IMG_20220315_084333.jpg](https://s2.loli.net/2022/03/15/Ukz9SDTiE18GpFd.jpg)

![Screenshot_2022-03-15-08-43-09-116_com.tencent.mm.jpg.png](https://s2.loli.net/2022/03/15/pWS8OsGIV12zx7i.jpg)

**Comment by xiaozhangtongx** [comment]
我也是，😭😭😭😭，我上完课回去看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月15日(周二) 上午8:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xiaozhangtongx/WHUT-JKRBTB] 打卡失败，小程序登录显示非法请求 (Issue #8)




 

 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Shmily-zd** [comment]
怎么说，是被封号了吗，要联系管理员吗

**Comment by Shmily-zd** [comment]
已经可以进系统了，所以说这是填报系统的问题吗

**Comment by xiaozhangtongx** [comment]
应该是的，系统的登录或认证出了问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月15日(周二) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaozhangtongx/WHUT-JKRBTB] 打卡失败，小程序登录显示非法请求 (Issue #8)




 
已经可以进系统了，所以说这是填报系统的问题吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Shmily-zd** [comment]
好的 大佬辛苦了
